# =========================
# Banco de dados
# =========================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/talentflow

# =========================
# Hibernate ORM
# =========================
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# =========================
# Flyway migrations
# =========================
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration
